{ pkgs, ... }: {
	systemd.settings.Manager = { DefaultLimitNOFILE = "524288"; };
	security.pam.loginLimits = [
		# core
		{ domain = "*";          type = "soft";    item = "core";       value = "0"; } # Prevent corefiles from being generated by default.
		{ domain = "*";          type = "hard";    item = "core";       value = "unlimited"; } # Allow corefiles to be temporarily enabled.
		
		# nice
		{ domain = "*";          type = "hard";    item = "nice";       value = "-19"; } # Prevent non-root users from running a process at minimal niceness.
		{ domain = "root";       type = "hard";    item = "nice";       value = "-20"; } # Allows root to run a process at minimal niceness to fix the systemwhenunresponsive.
		
		# nofile
		{ domain = "*";          type = "soft";    item = "nofile";     value = "8192"; } # Required for certain games to run.
		{ domain = "*";          type = "hard";    item = "nofile";     value = "524288"; } # Required for Esync to work properly.

		# nproc
		{ domain = "*";          type = "soft";    item = "nproc";      value = "4096"; }
		{ domain = "*";          type = "hard";    item = "nproc";      value = "8192"; } 
		{ domain = "root";       type = "hard";    item = "nproc";      value = "65536"; } # Prevent root from not being able to launch enough processes
		
		# priority
		{ domain = "*";          type = "soft";    item = "priority";   value = "0"; } # Set the default priority to neutral niceness.

		# memlock
    	{ domain = "*"; 		 type = "soft";    item = "memlock";    value = "unlimited"; } # Required for Fsync (Proton) to work optimally
    	{ domain = "*";          type = "hard";    item = "memlock";    value = "unlimited"; }
	];
}