# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	imports =
		[ (modulesPath + "/installer/scan/not-detected.nix")
		];

	boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "usbhid" "uas" "sd_mod" "rtsx_pci_sdmmc" ];
	boot.initrd.kernelModules = [ ];
	boot.kernelModules = [ "kvm-amd" ];
	boot.extraModulePackages = [ ];

	boot.initrd.luks.devices."nixos" = {
		device = "/dev/disk/by-uuid/e7d3419b-fc87-484f-ae9d-ea331d61c4b8";
		allowDiscards = true;
	};

	fileSystems."/" =
		{ device = "/dev/disk/by-uuid/a9a5e83e-c8ae-40fb-93e5-efbf4bfa4649";
			fsType = "btrfs";
			options = [ "subvol=@" "compress=zstd:1" "lazytime" "strictatime" ];
		};

	fileSystems."/nix" =
		{ device = "/dev/disk/by-uuid/a9a5e83e-c8ae-40fb-93e5-efbf4bfa4649";
			fsType = "btrfs";
			options = [ "subvol=@nix" "compress=zstd:1" "lazytime" "strictatime" ];
		};

	fileSystems."/home" =
		{ device = "/dev/disk/by-uuid/a9a5e83e-c8ae-40fb-93e5-efbf4bfa4649";
			fsType = "btrfs";
			options = [ "subvol=@home" "compress=zstd:1" "lazytime" "strictatime" ];
		};
  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/4016-9C6A";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B986-5E3A";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

	swapDevices = [ ];

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}



